import { Routes } from '@angular/router';
import { Main } from './pages/main/main';
import { Login } from './pages/login/login';
import { Register } from './pages/register/register';
import { Profile } from './pages/profile/profile';
import { MainAdmin } from './pages/main-admin/main-admin';
import { GameDetail } from './pages/game-detail/game-detail';
import { Cart } from './pages/cart/cart';
import { Wallet } from './pages/wallet/wallet';
import { Library } from './pages/library/library';
import { AddGame } from './pages/add-game/add-game';
import { EditGame } from './pages/edit-game/edit-game';
import { UserList } from './pages/user-list/user-list';
import { DiscountCode } from './pages/discount-code/discount-code';
import { UserHistory } from './pages/user-history/user-history';
export const routes: Routes = [
    
    { path: '', component: Main },
    { path: 'login', component: Login },
    { path: 'register', component: Register },
    { path: 'profile', component: Profile },
    { path: 'mainadmin', component: MainAdmin },
    { path: 'game/:id', component: GameDetail },
    { path: 'cart', component: Cart },
    { path: 'wallet', component: Wallet },
    { path: 'library', component: Library },
    { path: 'admin/add-game', component: AddGame },
    { path: 'admin/edit-game', component: EditGame },
    { path:  'admin/user-list', component: UserList },
    { path:  'admin/discount', component: DiscountCode },
    { path: 'admin/user-history', component: UserHistory },
];
